# Generated by Django 4.2.2 on 2023-07-02 13:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, verbose_name='Название')),
                ('type_discription', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы тестов',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=50, verbose_name='Название')),
                ('address', models.URLField(verbose_name='Адрес')),
                ('server_timeout', models.DurationField(default=datetime.timedelta(microseconds=400000), verbose_name='Ожидаемое время ответа сервера')),
                ('meta_data', models.JSONField(verbose_name='Мета данные (см. описание типа)')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auto_tests.testtype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
    ]
