# Generated by Django 4.2.2 on 2023-07-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_tests', '0002_test_test_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='address',
        ),
    ]
