# Generated by Django 4.2.2 on 2023-07-02 13:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(verbose_name='Пройден')),
                ('test_error', models.TextField(null=True, verbose_name='Ошибка теста')),
                ('server_timeout', models.DurationField(default=datetime.timedelta(microseconds=400000), verbose_name='Ожидаемое время ответа сервера')),
                ('date', models.DateTimeField(verbose_name='Дата прохождения теста')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auto_tests.test', verbose_name='Тест')),
            ],
        ),
    ]
